version: '3.8'

services:
  dms-postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - ./persistent/postgres-data/:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - dms-postgresql
    ports:
      - '8000:8000'
    # volumes:
    #   - ./server/dev-deploy/persistent/imported-data/:/var/lib/imported-data
    #   - ./server/dev-deploy/persistent/image-data/:/var/lib/image-data

  client:
      build:
        context: ./client
        dockerfile: Dockerfile
      ports:
        - "8080:80"