version: '3.8'

services:
  dms-postgresql:
    image: postgres:latest
    container_name: dms-postgresql
    env_file:
      - ./server/.env
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - ./server/data/postgresql/:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    depends_on:
      - dms-postgresql
    ports:
      - '8000:8000'

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
