env:
  browser: true
  es2021: true
  node: true
  es6: true
  mocha: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
extends: 'eslint:recommended'
plugins:
  - mocha
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-unused-vars: [ 'error', { argsIgnorePattern: ^_, varsIgnorePattern: ^_ } ]
  camelcase:
    - error
  array-bracket-spacing:
    - error
    - never
  brace-style:
    - error
    - 1tbs
  curly:
    - error
    - all
  no-mixed-spaces-and-tabs:
    - error
  no-trailing-spaces:
    - error
  no-redeclare:
    - error
  max-len:
    - error
    - 120
    - ignoreTrailingComments:
        true
    - ignoreTemplateLiterals:
        true
  eqeqeq:
    - error
    - smart
  eol-last:
    - warn
    - always
  no-useless-catch:
    - warn
  no-console:
    - error
